import { readFileSync, writeFileSync } from 'node:fs';
const shapes = ['K','Q','R','B','N','P'].map(type => {
  const svg = readFileSync(new URL(`../src/assets/cburnett/w${type}.svg`, import.meta.url), 'utf8');
  const body = svg.replace(/^.*?<svg[^>]*>/s, '').replace(/<\/svg>\s*$/, '')
    .replaceAll('fill="#fff"', 'fill="currentColor"').replaceAll('"#000"', '"#292621"')
    .replace(/(fill-rule|stroke-linecap|stroke-linejoin|stroke-width)/g, name => name.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase()));
  return `  ${type}: <>${body}</>,`;
});
writeFileSync(new URL('../src/Piece.tsx', import.meta.url), `// Generated by scripts/generate-pieces.mjs from the retained Cburnett SVG sources.
// Colin M. L. Burnett; GPL-2.0-or-later. See assets/cburnett/COPYING and THIRD_PARTY_NOTICES.md.
import type { PieceType } from "@li4chess/engine";
const shapes = {\n${shapes.join('\n')}\n};
export function Piece({ type, color, dead = false }: { type: PieceType; color: string; dead?: boolean }) {
  return <svg className="chess-piece" viewBox="0 0 45 45" aria-hidden="true" focusable="false" style={{ color: dead ? "#aaa69f" : color }}>{shapes[type]}</svg>;
}
`);
