import { expect, test } from "@playwright/test";

test("piece-owner letters default off and remember either choice without changing square names", async ({ page }) => {
  await page.goto("/li4chess/");
  await page.getByRole("button", { name: "Start game", exact: true }).click();
  const pawn = page.getByRole("button", { name: "g2 Red Pawn", exact: true });
  await expect(page.locator(".piece-owner")).toHaveCount(0);
  await page.getByText("Board display", { exact: true }).click();
  const toggle = page.getByLabel("Show piece-owner letters", { exact: true });
  await expect(toggle).not.toBeChecked();
  await toggle.check();
  await expect(pawn.locator(".piece-owner")).toHaveText("R");
  await pawn.click();
  await expect(pawn).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Save game", exact: true }).click();
  await expect(page.getByTestId("save-message")).toContainText("Saved on this browser");
  await page.reload();
  await page.getByRole("button", { name: "Resume saved game", exact: true }).click();
  await expect(pawn).toBeVisible();
  await expect(pawn.locator(".piece-owner")).toHaveText("R");
  await page.getByText("Board display", { exact: true }).click();
  await expect(toggle).toBeChecked();
  await toggle.uncheck();
  await expect(page.locator(".piece-owner")).toHaveCount(0);
  await page.reload();
  await page.getByRole("button", { name: "Resume saved game", exact: true }).click();
  await expect(pawn).toBeVisible();
  await expect(page.locator(".piece-owner")).toHaveCount(0);
  await page.getByText("Board display", { exact: true }).click();
  await expect(toggle).not.toBeChecked();
});
